### ISSUE TITLE
Multiple sections are not distinct enough from each other.

### ISSUE THREAD

**Issue by TristanWright** [Kitware/simput#6]
<img width="840" alt="screen shot 2016-02-05 at 17 33 23" src="https://cloud.githubusercontent.com/assets/13318121/12863028/24d0347c-cc2e-11e5-95f7-98fc0cf3cea8.png">
With some styling: 
```css
.prop-header {
    border-bottom: 4px solid #555; /* changed border width and color */
    width: 100%;
    padding: 10px 8px 3px;
    font-size: 1.1em;
    color: #111; /* changed color */
}

.InputBlock_header {
  color: #404040; /* changed color */
/* there are other attrs for this class but only color is changed */
}
```
We make the sections more distinct.
<img width="840" alt="screen shot 2016-02-05 at 17 31 52" src="https://cloud.githubusercontent.com/assets/13318121/12863025/1db741da-cc2e-11e5-84d7-a5c63c39e8ab.png">

CSS that controls these props is in Tonic-UI and is used in a lot of places there. Need to isolate this.
